# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Less CSS Guide

description: > # this means to ignore newlines until "baseurl:"
  This site is meant to demonstrate properties of Less and CSS.

baseurl: "/less-css-guide" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site

highlighter: rouge

# Build settings
markdown: kramdown

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - README.md