# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Front-end Style Guide
description: > # this means to ignore newlines until "baseurl:"
  This site is meant to help us unify our front-end code. These are the documented best-practises for front-end code structure. You can help us maintain this project by submitting your own examples of best practises you come across.
baseurl: "/style-guide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
highlighter: rouge

# Build settings
markdown: kramdown
